services:
  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ~/workspace/pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080