services:

  pg_main_1:
    build: ./pg-main
    ports:
      - "5445:5432"
    volumes:
      - mdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=doggo
      - POSTGRES_PASSWORD=rouf1234
      - POSTGRES_DB=petdb
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      - bridge-petwork

  pg_replica_1:
    build: ./pg-replica
    ports:
      - "5446:5432"
    volumes:
      - sdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=doggo
      - POSTGRES_PASSWORD=rouf1234
      - POSTGRES_DB=petdb
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    networks:
      - bridge-petwork

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pet.com
      - PGADMIN_DEFAULT_PASSWORD=adminadmin
    networks:
      - bridge-petwork

volumes:
  mdata:
  sdata:

networks:
  bridge-petwork:
    driver: bridge
