scope: cluster_1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.128.0.18:8008

bootstrap:
  dcs:
    ttl: 130
    loop_wait: 10
    retry_timeout: 60
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: 550
        max_locks_per_transaction: 512
        max_worker_processes: 27

  initdb:
    - encoding: UTF8
    - data-checksums

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.128.0.18:6432
  config_dir: /config
  data_dir: /var/lib/postgresql/data
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.128.0.18/32 md5
    - host replication replicator 10.128.0.98/32 md5
    - host replication replicator 10.128.0.99/32 md5
    - host all all 0.0.0.0/0 md5
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: supersecret

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false