server:
  port : ${SERVER_APP_PORT:8080}
spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5432}/petdb
    username: ${DB_CONNECTION_USERNAME:user}
    password: ${DB_CONNECTION_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db-changelog-${ENV:local}.yaml
springdoc:
  swagger-ui.path: /swagger-ui.html