apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-liquibaseinitcontainer-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-liquibaseinitcontainer-ms
  template:
    metadata:
      labels:
        app: dev-liquibaseinitcontainer-ms
        version: latest
    spec:
      nodeSelector:
      #        environment: {{ .Release.Name }}
      containers:
        - name: dev-liquibaseinitcontainer-ms
          image: leoyassuda/pet-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2000M"
            requests:
              memory: "800Mi"
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION_IP
              value: dev-postgres
            - name: LIQUIBASE_ENABLED
              value: "false"
      initContainers:
        - name: liquibase
          image: liquibase:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2000M"
            requests:
              memory: "200Mi"
          env:
            - name: DB_URL
              value: jdbc:postgresql://localhost:5432/petdb
            - name: DB_USERNAME
              value: doggo
            - name: DB_PASSWORD
              value: roufrouf
            - name: ENV
              value: dev
